IMAGE_NAME = "bento/centos-7"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box_download_insecure = true
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "m8tt-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "10.10.0.10"
        master.vm.hostname = "m8tt-master"
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "10.10.0.#{i + 10}"
            node.vm.hostname = "node-#{i}"
        end
    end
end
